### ISSUE TITLE
SSL certificaat is vervallen

### ISSUE THREAD

**Issue by janwerkhoven** [Sambego/annoying-recruiters#6]
Dag Sam,

Ik heb geen idee hoe je te bereiken, maar je website

https://blog.sambego.be/2015/12/05/using-ssl-on-digital-ocean-with-lets-encrypt/

Toont Chrome's red screen of death omdat je TLS certificaat is vervallen

![screen shot 2016-10-04 at 10 50 35 pm](https://cloud.githubusercontent.com/assets/4415419/19073215/8ccb3106-8a85-11e6-8a1a-6c1bd44c8db4.png)

![screen shot 2016-10-04 at 10 55 34 pm](https://cloud.githubusercontent.com/assets/4415419/19073248/b5f65bdc-8a85-11e6-92a3-415c5e5eda53.png)

![screen shot 2016-10-04 at 10 50 47 pm](https://cloud.githubusercontent.com/assets/4415419/19073216/8ccb63a6-8a85-11e6-9646-c6bd1f55572d.png)

Groeten vanuit Melbourne :)

**Comment by Sambego** [comment]
Hey @janwerkhoven, thanks voor het melden, er was iets mis gegaan met automatisch vernieuwen van het certificaat.

Bedankt om dit te melden, het is opgelost ondertussen :)
